# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.5.0" do
  arch arm: "arm64", intel: "x64"

  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "0ed7b89d9f3bf05bc8a265a0a44eceab8417b801053824f4c9646c50ed65ff71"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.5.0/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "93c238d7a492c6d99e1ec1b55e162a8d8db6e84397e6a0cd4aa637ee7b11a556"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.5.0/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "1aabc3875f8cff331ea89a38601ba5e002bd34d32483c5cc2e5b1247ba23a2ad"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.5.0/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
