# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.3" do
  arch arm: "arm64", intel: "x64"

  version "1.1.3"

  on_macos do
    on_arm do
      sha256 "41bcb4a470962eb3d3b70ef879f867f0509897f4b0070a9a9209210e8269f717"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.3/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "167d5bc4b907a6ffb3535574b6e23ade4c7b9687377ec386ad0f0bed15a7ffb0"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.3/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "b1271da595ee6d02787f172b721f01f1486dfdfec753516c71d1af602af841a1"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.3/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
