# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.5" do
  arch arm: "arm64", intel: "x64"

  version "1.1.5"

  on_macos do
    on_arm do
      sha256 "f6166928c301e8e0bab3d1b400949010956fcfd85ce87947eabdc929028a0edf"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.5/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "64418782356d528447f592f2b8cc736ea56371ca1f5d25a9aeb64fc26f5100e8"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.5/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "368033135f837eec15e11747d3483b59a74b4e24a4b138c9464dbd1f3fd87095"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.5/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
