# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.4" do
  arch arm: "arm64", intel: "x64"

  version "1.1.4"

  on_macos do
    on_arm do
      sha256 "f5cfbdd0117d5992488b69f475d0ca580c81b4dc73736228232d69b3a82255d8"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.4/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "b6ff5abee5d0973e71df4de5b4229edbf11b32fbb202a502104c0eb1120ab57b"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.4/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "f2f8bf1373182a1e6f0d11bdbe1ec028a35f348ed564796a6ea24eea35cfe587"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.4/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
