# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.10" do
  arch arm: "arm64", intel: "x64"

  version "1.1.10"

  on_macos do
    on_arm do
      sha256 "7e80ffd4f63ccf40c6a3728f9f555539ee05f83fbea59587d31c8b1888b26665"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.10/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "4197f97411ef31331d5e16e3476f691daaebea2f883a8c54bbbb6f72feed2d0d"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.10/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "f9a4a5a97d510a96cab95d23ef11013100c0abf233a6f082e5767fa6c4097236"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.10/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
