# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - the next Desktop release will overwrite this file.
cask "traycer-desktop" do
  arch arm: "arm64", intel: "x64"

  version "1.0.0"

  on_arm do
    sha256 "345c6df30f11bf4ae5b03ca47345920046ef1c6b007e120cfcabb2c85a07feee"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.0.0/traycer-desktop-macos-arm64.dmg"
  end

  on_intel do
    sha256 "ecb140a99751749ad4de55dafcf573348e69663f8ed49ee05bf453fd4a4ca2c3"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.0.0/traycer-desktop-macos-x64.dmg"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
  depends_on macos: ">= :monterey"

  app "Traycer.app"
end
