# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.4.2" do
  arch arm: "arm64", intel: "x64"

  version "1.4.2"

  on_macos do
    on_arm do
      sha256 "80e8b4cfe57008c25d040d28e1b928718ea34bce57eb9987a23432bff57719c8"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.2/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "5fb968ece981ae44593e8e319daf45c18f8466243c5e973c9911ebea029f36f0"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.2/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "3882767be040a2683716aef36b19558b9a3c8690c409a55462c3e92e26226f52"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.2/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
