# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.4.0" do
  arch arm: "arm64", intel: "x64"

  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "9b984788d5247d3bc35af08b3adbb77951fd388de6d4aad63d4585e6a2bf02f7"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.0/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "b48acad629d27c417d7f6803f4ada56fd648cd8a35a3c08d8c8b7cb005e9fd35"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.0/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "d74b8c6438a1f0e2907a09753e9088597ccd54a5604285e831f114f8be2cb12a"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.0/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
