# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - the next Desktop release will overwrite this file.
cask "traycer-desktop" do
  arch arm: "arm64", intel: "x64"

  version "1.1.1"

  on_arm do
    sha256 "fdfec77aee84f6f876656fce47f81eb3221bd0471ac65911a31222eeaf695085"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.1/traycer-desktop-macos-arm64.dmg"
  end

  on_intel do
    sha256 "a29d3c12c6cc2437967ab6f7c04755b635e16159659f5a8bb95c6e872d67723e"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.1/traycer-desktop-macos-x64.dmg"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
  depends_on macos: ">= :monterey"

  app "Traycer.app"
end
