# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.7" do
  arch arm: "arm64", intel: "x64"

  version "1.1.7"

  on_macos do
    on_arm do
      sha256 "bfc9597cc9eab9c35ed5b50cf7ef5422b3c82cb44cd6e8de8a4b0d76c3205bd5"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.7/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "f243613d05fc280f7e1c8444df3f15006614618f2d1d4afda663ad626f904f28"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.7/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "4ff7b09a32f7387e200f75702e2cf647cd1ca5c052f030c78060a513c0f4fe17"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.7/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
