# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.3.0" do
  arch arm: "arm64", intel: "x64"

  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "539f59298d2129154b3ab4764bf78b88f7709d4f78433f26672d7ba8fe5a9e12"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.3.0/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "ed8897a77501ef55d0a7325d5948d303842177bb31f167854a3110947e5d1cef"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.3.0/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "883a5ba43a5dd0e7911932b0515458888a514a5b670086f9f56fb221f1fc1c55"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.3.0/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
