# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - the next Desktop release will overwrite this file.
cask "traycer-desktop" do
  arch arm: "arm64", intel: "x64"

  version "1.1.0"

  on_arm do
    sha256 "c0f4a864202a8bc723bbbdc03a27e14ba17a3361b79fe33dd96b40dc97e518a9"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.0/traycer-desktop-macos-arm64.dmg"
  end

  on_intel do
    sha256 "2319cca62c6a8b33c9e810b845f3005b448452d6df77ae7866153557542b88a8"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.0/traycer-desktop-macos-x64.dmg"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
  depends_on macos: ">= :monterey"

  app "Traycer.app"
end
