# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.2.0" do
  arch arm: "arm64", intel: "x64"

  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "afc2ff7651948e3200fb5a1eada997e205c5a3abc4169237b694451e260ea59b"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.2.0/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "f6f8f5b5e0f56c293c58851913e4a5eff85bca5dc80e23e4b34670e6a185ae27"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.2.0/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "3eb2363445e2fb785cc9c109db16620c460585a2bfacc1686ec672acd784d888"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.2.0/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
