# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.4.1" do
  arch arm: "arm64", intel: "x64"

  version "1.4.1"

  on_macos do
    on_arm do
      sha256 "b0186044b33381715076984b77d20bf23f72633ca8ade992b55e69353ec50148"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.1/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "9c5370d8794099bf0c5bd4ede8225a006d3489b1489e97808bc33f3b8e9d5114"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.1/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "4d671d56342f21d6ea47e4fa2948ffd7379ab04ef148a4ea9cd6796936f8db9b"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.4.1/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
