# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.2" do
  arch arm: "arm64", intel: "x64"

  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "4231477d5166ba28ce1eb9228f2424093912da8b83263fe10c952e164e5ccdab"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.2/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "5f9c58b03b4def5dd415b619c1fa0e0305cc26900fe1f7ea8e9905dca80a5864"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.2/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "40da38f7bc28d62d9365d4efeeef8e49a3ea0ae9384d4a25730a32182aa77450"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.2/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
