# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.8" do
  arch arm: "arm64", intel: "x64"

  version "1.1.8"

  on_macos do
    on_arm do
      sha256 "38bbc3009ed32e84573f2bcb5cb680884214456fe511ad4a687a2b4cf8e05e41"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.8/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "4f7b54e661797e4a4326d1d1de1581784228e13486b6c935baf5688c22defcac"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.8/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "0b1c533f2790a2b355634e83ccb24d84db5040769c82f917e3a702de16b9d305"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.8/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
