# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Do not hand-edit - package-manager publishing regenerates this file.
cask "traycer-desktop@1.1.9" do
  arch arm: "arm64", intel: "x64"

  version "1.1.9"

  on_macos do
    on_arm do
      sha256 "db3a047ff98509315f94037b18d2adaf48eb3bc850c6b1f30a59a013ec277a97"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.9/traycer-desktop-macos-arm64.dmg"
    end

    on_intel do
      sha256 "436c54dff76e5065875de93b54382c2d8f2c8c584e6a7ac39f6a40f6930e2d6d"
      url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.9/traycer-desktop-macos-x64.dmg"
    end

    depends_on macos: :monterey

    app "Traycer.app"
  end
  # Linux AppImage casks require Homebrew >= 4.5.0.
  on_linux do
    depends_on arch: :x86_64

    sha256 "d02d3e73908560861d0cb6a48c9d06d4e7226ed30c071087073be1baef989d3b"
    url "https://github.com/traycerai/traycer/releases/download/desktop-v1.1.9/traycer-desktop-linux-x86_64.AppImage"

    appimage "traycer-desktop-linux-x86_64.AppImage"
  end

  name "Traycer"
  desc "Traycer desktop app"
  homepage "https://traycer.ai"

  auto_updates true
end
