# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.4
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT114 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.4"
  license "Apache-2.0"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.4/traycer-cli-macos-arm64"
      sha256 "13c89bd22726fb6bf6ccc8f60d6208fff3dcae5de555296219ab036e367baa18"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.4/traycer-cli-macos-x64"
      sha256 "0f2c90a41257474d6a98f81490b909e6ce285c1d6e1c7f2c9a56929876475098"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.4/traycer-cli-linux-arm64"
      sha256 "931e8c6e8aa5942c6d482d410a7c1b7cf5ffcc3048df982def97202e279abb26"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.4/traycer-cli-linux-x64"
      sha256 "9d7bcc256710c2f6bc33e865b53980b9f3364c1486af28be81e011c9f2259cbc"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
