# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.7
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT117 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.7"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.7/traycer-cli-macos-arm64"
      sha256 "a36067bae9557880a64d9b0abd94d72adf34e0d967249509623850e2aa4dfd41"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.7/traycer-cli-macos-x64"
      sha256 "7465b1bb38e28b27032aea4766eb92940c2a3552616ce0ec1d0cd1c69872f49d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.7/traycer-cli-linux-arm64"
      sha256 "a7720b39b340503c803b40208d4733d2800ead01d5b6b8f8353e075c2dcf3284"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.7/traycer-cli-linux-x64"
      sha256 "2c3bf0af025fa0249b88fed0a45db2863d586bfb498ca16e5c7070909a8605d7"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
