# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.2
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT112 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.2"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.2/traycer-cli-macos-arm64"
      sha256 "cccdda44be51cfc36be5c333da35cb89f3005555f1c3e8d08f822bd21eaf04af"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.2/traycer-cli-macos-x64"
      sha256 "83060b2125b2871045d957c9ddaec09e12f8f3d2f911301456237056b1420225"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.2/traycer-cli-linux-arm64"
      sha256 "7f5ba3861fba3969183d954516e1dafadd1a76aa592d23ae2e5c23e3b1770c66"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.2/traycer-cli-linux-x64"
      sha256 "512b31b57558f018b3cc069399e7cd243da865f938b73be4a2f1e6e916fb5ed9"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
