# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.1
# Do not hand-edit - the next CLI release will overwrite this file.
class Traycer < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.1/traycer-cli-macos-arm64"
      sha256 "86ccb4507c48dcdce279e297dfd8d4dc5114a993c44d8d52e0374af53df6e74d"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.1/traycer-cli-macos-x64"
      sha256 "423afa4c1004e9ac43c215a18b7f941ef7ff53cd4cba84e40e3b15b43869073e"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.1/traycer-cli-linux-arm64"
      sha256 "d7d2f018a0fc5e996a2bdf31ac13ec44d0b995082879bd29685e554db2135411"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.1/traycer-cli-linux-x64"
      sha256 "f36ead8894d849c47ac2923662f01bf74f94bbbbe8b07de9437bf00ebd205d81"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
