# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.5.0
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT150 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.5.0"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.5.0/traycer-cli-macos-arm64"
      sha256 "072e8288dc4515945ae89d6749bad1fad8465f573a4612ab3ed11d9766402195"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.5.0/traycer-cli-macos-x64"
      sha256 "520ea9a0468929232dfe3ef9172de48b461cc0e2a265f8d4120ce7b6b9401ea1"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.5.0/traycer-cli-linux-arm64"
      sha256 "989b7f2eb193eac6741feb63abc797e6ed39ef10b877816bc9ec44b38e3c1af6"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.5.0/traycer-cli-linux-x64"
      sha256 "ab7fa9b6590d5800d406859ad367d1b2d9d3bec36053483d0581abbf27a57312"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
