# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.4.0
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT140 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.4.0"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.0/traycer-cli-macos-arm64"
      sha256 "50c306cd5686d6492f771538c79002bfd02b2c9d64bb4a912f317108eb3bcbdb"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.0/traycer-cli-macos-x64"
      sha256 "5fafabd5531ea3cce864925efa7f13b1b4293079e6dce214846a90965f4f0c5e"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.0/traycer-cli-linux-arm64"
      sha256 "23a34ff0db070ba80d2675b8ca22ce679c59681fe8aa1286f3de58afdf30c317"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.0/traycer-cli-linux-x64"
      sha256 "cccb167d4815ee35fb0c49f89945a18fc562a34511702d763b8450998d05de04"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
