# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.9
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT119 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.9"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.9/traycer-cli-macos-arm64"
      sha256 "1eb03a902af8e9f02b541d24e014b232575b34acac40eeb08842f37a36c09e79"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.9/traycer-cli-macos-x64"
      sha256 "d067c4fc3565f0b068538de41c8aaf5fddc07feb7ff741b236545994e3eff951"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.9/traycer-cli-linux-arm64"
      sha256 "8b254f4d107277db957d6569c04e51512935ff6e83ea25b92d399be5221230f2"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.9/traycer-cli-linux-x64"
      sha256 "542e9b1ec3e2cd9210e0e6bb600143cb0117dbc93793efeb2864f7ec747d1b31"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
