# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.10
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT1110 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.10"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.10/traycer-cli-macos-arm64"
      sha256 "8f32118a00cab85bc08ea1e65d74b1dd36b6347143f7be7a7eebd85e1351055f"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.10/traycer-cli-macos-x64"
      sha256 "51ddfc741af96bf19fc66ab2aeff8cec8ad37bf2e0da58fd171ec52bf5ad8ec3"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.10/traycer-cli-linux-arm64"
      sha256 "5f9de2495162941d2afeb6bcc8e63ba9992e8123d57e347fea6ea11551553ebb"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.10/traycer-cli-linux-x64"
      sha256 "302d7534992378379ed6fca4157c5ce0c586a4d74a9ffdfc3be86e24f46bf055"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
