# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.3
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT113 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.3"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.3/traycer-cli-macos-arm64"
      sha256 "ec5a941310806fbefd0fe93d07728124194fa455e856aa32c4047ec62ff7b6c1"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.3/traycer-cli-macos-x64"
      sha256 "6ed66bd86656bd65d1c7f29c77109f8d33c451a7eee57e6b03ea9a062e5111d1"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.3/traycer-cli-linux-arm64"
      sha256 "8af72dbce4c7a4c9922ad4a95e976cddcd44312997738ad9619d2a492ffc2ae6"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.3/traycer-cli-linux-x64"
      sha256 "3ab1df8e1d9dce657fe1364d9bb57dcb4d7038bf9e3ae1bb8a10fc639fbc5fd3"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
