# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.0.0
# Do not hand-edit - the next CLI release will overwrite this file.
class Traycer < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.0.0/traycer-cli-macos-arm64"
      sha256 "1a7f239db9a4266a0ca307055178850c131632a0e3a5d6f31701ea2d400360a1"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.0.0/traycer-cli-macos-x64"
      sha256 "609ab1430a7847ebd891dbe78fc5b478d06ff1fd98e075ca85324f71701b384b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.0.0/traycer-cli-linux-arm64"
      sha256 "5f3944d2d3754e9a41ec15b4262199f0d95cd77efa0dd7260e45f20613fb7983"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.0.0/traycer-cli-linux-x64"
      sha256 "904a69c2daf4cca303ba94e154451e94508e9e9714b7926bdc35c6ba46e62253"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
