# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.8
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT118 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.8"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.8/traycer-cli-macos-arm64"
      sha256 "5d9ca9f57ac469b7e701d6afbcdc1739e4a270c1a57864f05d0a4d08f67b2bf4"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.8/traycer-cli-macos-x64"
      sha256 "2033871dc9cae93cf10dff2d6b8146e4a7517d872cbe9947872f0c4b19393766"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.8/traycer-cli-linux-arm64"
      sha256 "926e7e2a833a049db0744299b1e222eef170f3d58af1db5bf35939275e4ab5ce"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.8/traycer-cli-linux-x64"
      sha256 "55c83eea6d742b8d68e1c745ca1084fa2776b9b250a1a2bc47cd732c8287046d"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
