# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.4.2
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT142 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.4.2"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.2/traycer-cli-macos-arm64"
      sha256 "5c0d9aa15815edd674fe5bc0189dd81817a3ff6a047c74c43bdbbb97f25c4c3c"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.2/traycer-cli-macos-x64"
      sha256 "f8ca083c0c8c434d7c03c945b22b19f2ec6bb78e8d72b7834a62e3ec1f1d3a20"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.2/traycer-cli-linux-arm64"
      sha256 "924e65ffd4c2be3775e089c9a37288e5c951fa7b619ed772b6099aa0994fe185"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.4.2/traycer-cli-linux-x64"
      sha256 "c4a81c90da6b8fa9e672c6190463e6a9413f129be003bd786cff88403b1e1eac"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
