# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.6
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT116 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.6"
  license "Apache-2.0"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.6/traycer-cli-macos-arm64"
      sha256 "4a9e651551a1d949444e1d9e8a9154ecc2639c9832a436c89ac50dfe3cd14968"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.6/traycer-cli-macos-x64"
      sha256 "4025f3df0f3adcd8c3f48842cf33f1e35ccf8596f7b17bbab1d75598143b8557"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.6/traycer-cli-linux-arm64"
      sha256 "89b8e7ea5694a786bc7b50abf8a6d3806df9548ddb00e5b59bf4f9800260bc88"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.6/traycer-cli-linux-x64"
      sha256 "889772d9acea4b19f6579256b59a66ac180535d25de6a7267e4fd81d5a086967"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
