# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.2.0
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT120 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.2.0"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.2.0/traycer-cli-macos-arm64"
      sha256 "08a75c09722d4bd260c541e4b763433870a02e3e1b2d2f1d7d745e7adb0d3bd9"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.2.0/traycer-cli-macos-x64"
      sha256 "4d7240089e55ffd1e8a4e5332578df7c7a99172944ceeda87a16e02110d74d80"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.2.0/traycer-cli-linux-arm64"
      sha256 "88503096c825ab8a967f6408317ca2995993cd4a100c85968f0084e6f923566b"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.2.0/traycer-cli-linux-x64"
      sha256 "eef2adc1ff5e9aaa001e82b5e323ee44bc54a3e8ade1444c26e41b9fa35d0958"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
