# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.3.0
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT130 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.3.0"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.3.0/traycer-cli-macos-arm64"
      sha256 "452661ab635c2d9605398a3255f53c59b98007066ff68c49752d34e699d8dc58"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.3.0/traycer-cli-macos-x64"
      sha256 "9c47aa8a50f9c72d2dd8de051c6084380d2cdc95c9de67c10c64d8123c51ef83"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.3.0/traycer-cli-linux-arm64"
      sha256 "70b2f2e9facc22aacebcfb900a03684bfffbf22e86c5bc60eb39ef43c92933fb"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.3.0/traycer-cli-linux-x64"
      sha256 "fdc78e6ad8e686d5a3b6f07a7334d28361489efd294edf693e61b346587537c3"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
