# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.5
# Do not hand-edit - package-manager publishing regenerates this file.
class TraycerAT115 < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.5"
  license "Apache-2.0"

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.5/traycer-cli-macos-arm64"
      sha256 "3602517eee566b4d533c500c06ecc0f09c06ca353a96f233dab44d6369457f75"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.5/traycer-cli-macos-x64"
      sha256 "20e50068b2f889f1671fda4379d97a1b1f478f722aa74f91d724ed1dbb13c7f4"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.5/traycer-cli-linux-arm64"
      sha256 "044a0749a1e5152cb622d8d3ca494025fa1d320318e9c310e98c0e02aad4d870"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.5/traycer-cli-linux-x64"
      sha256 "432c1cce4611dc4fab54be1f90f21b968080f8021702a8dcb0812c4ec884cfef"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
