# Auto-generated by scripts/native-packaging/publish-cli-package-managers.cjs
# Source: https://github.com/traycerai/traycer/releases/tag/cli-v1.1.0
# Do not hand-edit - the next CLI release will overwrite this file.
class Traycer < Formula
  desc "Traycer CLI - host supervisor, auth, and config surface"
  homepage "https://traycer.ai"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.0/traycer-cli-macos-arm64"
      sha256 "ced55586bfe325f3e0532963e2ad87594cfd8b7a4f18862365f50ccdf9140776"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.0/traycer-cli-macos-x64"
      sha256 "fa2434b4691ac5f86a1bf5e82a6f0059173732b972022792283b16c145e6901c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.0/traycer-cli-linux-arm64"
      sha256 "454322fd1686b748bf49341013407a9a83e0cc809e1607a9ce8eff2a4efed5ac"
    end
    on_intel do
      url "https://github.com/traycerai/traycer/releases/download/cli-v1.1.0/traycer-cli-linux-x64"
      sha256 "1115c3ae90ff6d8baf79ac11de642cf669455c76be13418a274ba4b4a0ca1aee"
    end
  end

  def install
    bin.install Dir["traycer*"].first => "traycer"
    # Mark this install as homebrew-owned so 'traycer cli upgrade' guides
    # the user to 'brew upgrade traycer' instead of self-replacing. Only the
    # mark-source call is best-effort (it writes the CLI install manifest if
    # the user's home is writable) - a failed bin.install above must still
    # fail the formula rather than be swallowed.
    begin
      system bin/"traycer", "cli", "mark-source", "--source", "homebrew",
             "--binary-path", bin/"traycer", "--installed-version", version
    rescue
      nil
    end
  end

  test do
    # 'traycer --version' prints only a semver-shaped version string
    # (no 'traycer' prefix). We pin two checks:
    #   1. The reported value matches the released formula version
    #      exactly. This catches release artifacts that were built
    #      without TRAYCER_CLI_VERSION (which would otherwise report
    #      the source-tree placeholder "0.0.0-local" or a stale
    #      "0.0.0"); a generic /^\d+\.\d+\.\d+/ shape match would
    #      let those slip through.
    #   2. As defence in depth, reject the literal placeholders so a
    #      future formula refactor that loosens (1) still cannot ship a
    #      placeholder build.
    reported = shell_output("#{bin}/traycer --version").strip
    assert_equal version.to_s, reported
    refute_match(/\A0\.0\.0(?:-local)?\z/, reported)
  end
end
